### PR TITLE
Add SUPPORT_CLUSTER_REPORT to list of capabilities

### PR DESCRIPTION
**Pull request by darkonie**

### CODE REVIEW

**Comment by BenWhitehead** [comment]
What does `SNAPSHOT_MANAGEMENT` mean? I think we may want a more specific name for this capability.

**Comment by darkonie** [comment]
@BenWhitehead fixed

**Comment by tamarrow** [comment]
thanks @darkonie!

**Comment by BenWhitehead** [comment]
@darkonie Can you apply the following patch so the tests will pass:
```patch
Index: cosmos-server/src/it/scala/com/mesosphere/cosmos/handler/CapabilitiesHandlerSpec.scala
<+>UTF-8
===================================================================
--- cosmos-server/src/it/scala/com/mesosphere/cosmos/handler/CapabilitiesHandlerSpec.scala	(date 1466799449000)
+++ cosmos-server/src/it/scala/com/mesosphere/cosmos/handler/CapabilitiesHandlerSpec.scala	(date 1466803239000)
@@ -20,6 +20,10 @@
     assertResult(Status.Ok)(response.status)
     assertResult(MediaTypes.CapabilitiesResponse.show)(response.headerMap("Content-Type"))
     val Xor.Right(body) = decode[CapabilitiesResponse](responseBody)
-    assertResult(CapabilitiesResponse(List(Capability("PACKAGE_MANAGEMENT"))))(body)
+    val expected = CapabilitiesResponse(List(
+      Capability("PACKAGE_MANAGEMENT"),
+      Capability("SUPPORT_CLUSTER_REPORT")
+    ))
+    assertResult(expected)(body)
   }
 }

```

**Comment by darkonie** [comment]
@BenWhitehead done

**Comment by tamarrow** [comment]
🎉

**Pull request merged**
