### PR TITLE
add dcos-log capability

### PR DESCRIPTION
**Pull request by darkonie**
with 1.10 release we are going to use new `dcos-log` backend for cluster logs.
That said UI and CLI need a new capability to recognize supported clusters.

Related PRs
DC/OS:
https://github.com/dcos/dcos/pull/832

DC/OS CLI:
https://github.com/dcos/dcos-cli/pull/817

dcos-log project:
https://github.com/dcos/dcos-log

### CODE REVIEW

**Comment by darkonie** [comment]
let me know if DCOS_LOG is not a very good capability name

**Comment by jsancio** [comment]
@darkonie I would call it LOGGING or maybe CONTAINER_LOGGING. What do you think?

**Comment by darkonie** [comment]
@jsancio LOGGING sounds good to me. CONTAINER_LOGGING isn't a very good one because this API will also provide host and containers logs.

**Comment by darkonie** [comment]
@jsancio PR updated. However let's not remove 'do not merge' label for now. this should go in 1.10

**Comment by jsancio** [comment]
Sounds good @darkonie. Let us know when you are ready.

**Comment by adam-mesos** [comment]
@darkonie Looks like this might need a rebase

**Comment by darkonie** [comment]
@adam-mesos @jsancio rebased. Can we merge this?

**Comment by jsancio** [comment]
@darkonie I have updated the branch with the latest master. I will merge it once it passes. I will also make sure that it gets included in DC/OS.

**Pull request merged**
